defaults:
  - _self_
  - dir: local
  - feature: dino_giant
  - model: lasso
  - training: default
  - override hydra/job_logging: disabled

exp_name: ml_baseline

hydra:
  run:
    dir: ${dir.output_dir}/${exp_name}
