defaults:
  - _self_
  - dir: local

  # === 使用するコンポーネント ===
  # DINO+Lassoのときは feature, model, training
  # ConvNeXtのときは model, inference

  # デフォルト（とりあえずnullにしておくか、よく使うものを指定）
  - feature: null
  - model: convnext # 今回追加したもの
  - inference: convnext # 今回追加したもの
  - training: null # 推論だけなら不要
  - override hydra/job_logging: disabled

exp_name: convnext_inference

hydra:
  run:
    dir: ${dir.output_dir}/${exp_name}
