defaults:
  - _self_
  - dir: local
  - dataset: null
  - feature: null
  - model: convnext
  - inference: convnext # 今回追加したもの
  - training: null # 推論だけなら不要
  - experiment: null
  - transform: null
  - override hydra/job_logging: disabled

normalization: "standard"
wandb_mode: "online"
exp_name: test

hydra:
  run:
    dir: ${dir.output_dir}/${exp_name}
